avoid String#format
bacause scala-native 0.2.1 does not support this

https://github.com/scala-native/scala-native/blob/v0.2.1/javalib/src/main/scala/java/util/Formatter.scala#L22-L24

```
scala.NotImplementedError: an implementation is missing
	at java.lang.Throwable::init_java.lang.String_java.lang.Throwable
	at java.lang.Error::init_java.lang.String_java.lang.Throwable
	at java.lang.Error::init_java.lang.String
	at scala.NotImplementedError::init_java.lang.String
	at scala.NotImplementedError::init
	at scala.Predef$::???_nothing
	at java.util.Formatter::format_java.lang.String_scala.scalanative.runtime.ObjectArray_java.util.Formatter
	at java.lang.String$::format_java.util.Locale_java.lang.String_scala.scalanative.runtime.ObjectArray_java.lang.String
	at java.lang.String$::format_java.lang.String_scala.scalanative.runtime.ObjectArray_java.lang.String
	at scala.collection.immutable.StringLike$class$::format_scala.collection.immutable.StringLike_scala.collection.Seq_java.lang.String
	at scala.collection.immutable.StringOps::format_scala.collection.Seq_java.lang.String
	at argonaut.PrettyParams$$anonfun$1::apply_i32_java.lang.String
	at argonaut.PrettyParams$$anonfun$1::apply_java.lang.Object_java.lang.Object
	at scala.collection.generic.GenTraversableFactory::tabulate_i32_scala.Function1_scala.collection.GenTraversable
	at argonaut.PrettyParams$$anonfun$vectorMemo$1::apply_i32_java.lang.String
	at argonaut.PrettyParams$$anonfun$vectorMemo$1::apply_java.lang.Object_java.lang.Object
	at argonaut.PrettyParams::argonaut$PrettyParams$$lbrace$1_scala.collection.mutable.StringBuilder_i32_scala.collection.mutable.StringBuilder
	at argonaut.PrettyParams$$anonfun$argonaut$PrettyParams$$trav$1$6::apply_argonaut.JsonObject_scala.collection.mutable.StringBuilder
	at argonaut.PrettyParams$$anonfun$argonaut$PrettyParams$$trav$1$6::apply_java.lang.Object_java.lang.Object
	at argonaut.Json::fold_scala.Function0_scala.Function1_scala.Function1_scala.Function1_scala.Function1_scala.Function1_java.lang.Object
	at argonaut.PrettyParams::argonaut$PrettyParams$$trav$1_scala.collection.mutable.StringBuilder_i32_argonaut.Json_scala.collection.mutable.StringBuilder
	at argonaut.PrettyParams::pretty_argonaut.Json_java.lang.String
	at argonaut.Json::nospaces_java.lang.String
	at argonaut.Json::toString_java.lang.String
```